---
title: "Homework template"
subtitle: "class and assignment"
author: "YOUR_NAME_HERE"
date: "`r format(Sys.time(), '%F')`"
format: 
  html:
      theme: 
        - cosmo
        - _extensions/hw-html/THEME_FILE_HERE
      linkcolor: "#0000EE"
      toc: true
      toc-title: "Problems and Exercises"
      embed-resources: true
      link-external-newwindow: true
---

# Question 1

Describe the problem set here

## Answer 1

Answer the question here.

| Model | Variable $\beta_0$ | Coefficient $\beta_1$ |
|-------|--------------------|-----------------------|
| A     | 1.5                | 1.9                   |
| B     | 1.1                | 1.7                   |

Write up your code if necessary.

```{r}
#| label: answer 1

1 + 3

```

# Question 2

Describe question 2 here.

## Part A

This is a 2 part question. This is the first part.

## Answer 2 A

Here is the answer to part A.

$$
x \sim B(n,p) \\
n \in \{0, 1, 2, 3, ...\} \\
p \in [0, 1]
$$

## Part B

Here is the second part of the question.

## Answer 2 B

Here is the answer to part B.

```{r}
#| label: answer 2b

set.seed(101)

x <- rnorm(100, mean = 5, sd = 2)

avg_x <- mean(x) |> round(1)

sd_x <- sd(x) |> round(1)

print(paste0("The mean of x is ", avg_x, " and the standard deviation of x is ", sd_x, "."))

```
